// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate Supabase environment variables
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  const missing = [];
  if (!SUPABASE_URL) missing.push('VITE_SUPABASE_URL');
  if (!SUPABASE_ANON_KEY) missing.push('VITE_SUPABASE_ANON_KEY');

  console.error(`Missing required environment variables: ${missing.join(', ')}. Please check your environment configuration.`);
}

// Resolve the final URL and key, falling back to placeholders if env vars
// are missing. The Supabase SDK throws "supabaseUrl is required" if given
// an empty string, which would crash the app at module-load time.
//
// NOTE: We resolve these into named constants BEFORE passing to createClient
// to avoid any minifier reordering of the `||` expressions. Earlier Vercel
// builds had the arguments swapped due to minifier optimization of inline
// `||` expressions — using explicit constants eliminates that ambiguity.
const PLACEHOLDER_URL = 'https://placeholder.supabase.co';
const PLACEHOLDER_KEY = 'placeholder-anon-key';

const resolvedUrl: string = SUPABASE_URL || PLACEHOLDER_URL;
const resolvedKey: string = SUPABASE_ANON_KEY || PLACEHOLDER_KEY;

// Create the Supabase client. Signature: createClient(supabaseUrl, supabaseKey, options)
export const supabase: SupabaseClient<Database> = createClient<Database>(
  resolvedUrl,
  resolvedKey,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      flowType: 'pkce',
    }
  }
);

// Build trigger: force Vercel to rebuild from latest source.
