// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate Supabase environment variables
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  const missing = [];
  if (!SUPABASE_URL) missing.push('VITE_SUPABASE_URL');
  if (!SUPABASE_ANON_KEY) missing.push('VITE_SUPABASE_ANON_KEY');

  console.error(`Missing required environment variables: ${missing.join(', ')}. Please check your environment configuration.`);
}

// Create the Supabase client.
//
// When env vars are missing, we pass placeholder values to createClient
// instead of empty strings. The Supabase SDK throws "supabaseUrl is
// required" if given an empty string, which would crash the app at
// module-load time — before React mounts, before ConfigErrorPage can
// render, and before any user sees a helpful message.
//
// With placeholder values, the client is constructed successfully and the
// app boots. Any actual API call will fail (401/auth error), but by then
// ConfigErrorPage has already rendered with clear instructions.
//
// The App.tsx isConfigured() check happens before any provider that
// would use this client, so the user sees the config error page rather
// than a broken auth flow.
const PLACEHOLDER_URL = 'https://placeholder.supabase.co';
const PLACEHOLDER_KEY = 'placeholder-anon-key';

export const supabase: SupabaseClient<Database> = createClient<Database>(
  SUPABASE_URL || PLACEHOLDER_URL,
  SUPABASE_ANON_KEY || PLACEHOLDER_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      flowType: 'pkce',
    }
  }
);
